#cmsRun recHitRAW_cfg.py runNumber=325711 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source outputTag=_normedTree emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325774 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source outputTag=_normedTree emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325792 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source skipEvents=0 outputTag=_normed emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=325897 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source skipEvents=0 outputTag=_normed emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=325906 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source skipEvents=0 outputTag=_normed emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=325915 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source skipEvents=0 outputTag=_normed emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=325921 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source skipEvents=0 outputTag=_normedTree emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325959 runInputDir=/eos/cms/store/express/HIRun2018/ExpressCosmics/FEVT/Express-v1/000/ source=PoolSource rawTag=rawDataCollector outputTag=_normedRandomTree hlt=HLT_Random_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325967 runInputDir=/eos/cms/store/hidata/HIRun2018/ZeroBias/RAW/v1/000/ source=PoolSource rawTag=rawDataCollector outputTag=_normedRandomTree hlt=HLT_Random_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325978 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag=rawDataRepacker outputTag=_normedRandomTree hlt=HLT_HIRandom_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325978 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag='' outputTag=_normedRandomTree_t hlt=HLT_HIRandom_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325994 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag='' outputTag=_normedRandomTree hlt=HLT_HIRandom_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325988 runInputDir=/eos/cms/store/express/HIRun2018/ExpressCosmics/FEVT/Express-v1/000/ source=PoolSource rawTag=rawDataCollector outputTag=_normedRandomTree hlt=HLT_Random_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325989 runInputDir=/eos/cms/store/express/HIRun2018/ExpressCosmics/FEVT/Express-v1/000/ source=PoolSource rawTag=rawDataCollector outputTag=_normedRandomTree hlt=HLT_Random_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326000 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag='' outputTag=_normedRandomTree hlt=HLT_HIRandom_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325994 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag='' outputTag=_normedRandomTree hlt=HLT_HIRandom_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=324980 runInputDir=/eos/cms/store/data/Run2018D/ZeroBias/RAW/v1/000/ source=PoolSource rawTag='rawDataCollector' outputTag=_normedRandomTree hlt=HLT_Random_v emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=325774 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source outputTag=_normed emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=326151 runInputDir=/eos/cms/store/express/HIRun2018/ExpressCosmics/FEVT/Express-v1/000/ source=PoolSource rawTag=rawDataCollector outputTag=_normedRandom emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=326189 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag='' outputTag=_normedRandom hlt=HLT_HIRandom_v normed=True
#cmsRun recHitRAW_cfg.py runNumber=326175 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag='' outputTag=_normedZB hlt=HLT_HIZeroBias_v emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=326175 runInputDir=/eos/cms/store/hidata/HIRun2018/HIForward/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedZB_calib hlt=HLT_HIZeroBias_v emap=reduced normed=True
#cmsRun recHitRAW_cfg.py runNumber=326238 runInputDir=/eos/cms/store/hidata/HIRun2018/HIMinimumBias1/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB1Tree hlt=HLT_HIMinimumBias_part1_v emap=reduced normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326238 runInputDir=/eos/cms/store/hidata/HIRun2018/HIMinimumBias2/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB2Tree hlt=HLT_HIMinimumBias_part2_v emap=reduced normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326238 runInputDir=/eos/cms/store/hidata/HIRun2018/HIMinimumBias3/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB3Tree hlt=HLT_HIMinimumBias_part3_v emap=reduced normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326238 runInputDir=/eos/cms/store/hidata/HIRun2018/HIMinimumBias4/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB4Tree hlt=HLT_HIMinimumBias_part4_v emap=reduced normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326238 runInputDir=/eos/cms/store/hidata/HIRun2018/HIMinimumBias5/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB5Tree hlt=HLT_HIMinimumBias_part5_v emap=reduced normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326238 runInputDir=/eos/cms/store/hidata/HIRun2018/HIMinimumBias6/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB6Tree hlt=HLT_HIMinimumBias_part6_v emap=reduced normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326238 runInputDir=/eos/cms/store/hidata/HIRun2018/HIMinimumBias7/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB7Tree hlt=HLT_HIMinimumBias_part7_v emap=reduced normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326238 runInputDir=/eos/cms/store/hidata/HIRun2018/HIMinimumBias8/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB8Tree hlt=HLT_HIMinimumBias_part8_v emap=reduced normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326238 runInputDir=/eos/cms/store/hidata/HIRun2018/HIMinimumBias9/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB9Tree hlt=HLT_HIMinimumBias_part9_v emap=reduced normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326238 runInputDir=/eos/cms/store/hidata/HIRun2018/HIMinimumBias0/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB0Tree hlt=HLT_HIMinimumBias_part0_v emap=reduced normed=True bTree=True

cmsRun recHitRAW_cfg.py runNumber=326482 runInputDir=/eos/cms/store/hidata/HIRun2018A/HIMinimumBias0/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB0PedTree hlt=HLT_HIMinimumBias_part0_v emap=reduced normed=True bTree=True
cmsRun recHitRAW_cfg.py runNumber=326482 runInputDir=/eos/cms/store/hidata/HIRun2018A/HIMinimumBias1/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB1PedTree hlt=HLT_HIMinimumBias_part1_v emap=reduced normed=True bTree=True
cmsRun recHitRAW_cfg.py runNumber=326482 runInputDir=/eos/cms/store/hidata/HIRun2018A/HIMinimumBias2/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB2PedTree hlt=HLT_HIMinimumBias_part2_v emap=reduced normed=True bTree=True
cmsRun recHitRAW_cfg.py runNumber=326482 runInputDir=/eos/cms/store/hidata/HIRun2018A/HIMinimumBias3/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB3PedTree hlt=HLT_HIMinimumBias_part3_v emap=reduced normed=True bTree=True
cmsRun recHitRAW_cfg.py runNumber=326482 runInputDir=/eos/cms/store/hidata/HIRun2018A/HIMinimumBias4/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB4PedTree hlt=HLT_HIMinimumBias_part4_v emap=reduced normed=True bTree=True
cmsRun recHitRAW_cfg.py runNumber=326482 runInputDir=/eos/cms/store/hidata/HIRun2018A/HIMinimumBias5/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB5PedTree hlt=HLT_HIMinimumBias_part5_v emap=reduced normed=True bTree=True
cmsRun recHitRAW_cfg.py runNumber=326482 runInputDir=/eos/cms/store/hidata/HIRun2018A/HIMinimumBias6/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB6PedTree hlt=HLT_HIMinimumBias_part6_v emap=reduced normed=True bTree=True
cmsRun recHitRAW_cfg.py runNumber=326482 runInputDir=/eos/cms/store/hidata/HIRun2018A/HIMinimumBias7/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB7PedTree hlt=HLT_HIMinimumBias_part7_v emap=reduced normed=True bTree=True
cmsRun recHitRAW_cfg.py runNumber=326482 runInputDir=/eos/cms/store/hidata/HIRun2018A/HIMinimumBias8/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB8PedTree hlt=HLT_HIMinimumBias_part8_v emap=reduced normed=True bTree=True
cmsRun recHitRAW_cfg.py runNumber=326482 runInputDir=/eos/cms/store/hidata/HIRun2018A/HIMinimumBias9/RAW/v1/000/ source=PoolSource rawTag='rawDataRepacker' outputTag=_normedMB9PedTree hlt=HLT_HIMinimumBias_part9_v emap=reduced normed=True bTree=True

#cmsRun recHitRAW_cfg.py runNumber=326537 runInputDir=/eos/cms/store/express/HIRun2018A/ExpressCosmics/FEVT/Express-v1/000/ source=PoolSource rawTag='rawDataCollector' outputTag=_normedRandomTree hlt='HLT_Random_v' emap=reduced normed=True bTree=True bPedestal=True
