#cmsRun recHitRAW_cfg.py runNumber=325711 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source outputTag=_normedTree emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325774 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source outputTag=_normedTree emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325792 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source skipEvents=0 outputTag=_normed emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=325897 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source skipEvents=0 outputTag=_normed emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=325906 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source skipEvents=0 outputTag=_normed emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=325915 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source skipEvents=0 outputTag=_normed emap=ext normed=True
#cmsRun recHitRAW_cfg.py runNumber=325921 runInputDir=/eos/cms/store/group/dpg_hcal/comm_hcal/USC source=HcalTBSource rawTag=source skipEvents=0 outputTag=_normedTree emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325959 runInputDir=/eos/cms/store/express/HIRun2018/ExpressCosmics/FEVT/Express-v1/000/ source=PoolSource rawTag=rawDataCollector outputTag=_normedRandomTree hlt=HLT_Random_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325967 runInputDir=/eos/cms/store/hidata/HIRun2018/ZeroBias/RAW/v1/000/ source=PoolSource rawTag=rawDataCollector outputTag=_normedRandomTree hlt=HLT_Random_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325978 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag=rawDataRepacker outputTag=_normedRandomTree hlt=HLT_HIRandom_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325978 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag='' outputTag=_normedRandomTree_t hlt=HLT_HIRandom_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325994 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag='' outputTag=_normedRandomTree hlt=HLT_HIRandom_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325988 runInputDir=/eos/cms/store/express/HIRun2018/ExpressCosmics/FEVT/Express-v1/000/ source=PoolSource rawTag=rawDataCollector outputTag=_normedRandomTree hlt=HLT_Random_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=325989 runInputDir=/eos/cms/store/express/HIRun2018/ExpressCosmics/FEVT/Express-v1/000/ source=PoolSource rawTag=rawDataCollector outputTag=_normedRandomTree hlt=HLT_Random_v emap=ext normed=True bTree=True
#cmsRun recHitRAW_cfg.py runNumber=326000 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag='' outputTag=_normedRandomTree hlt=HLT_HIRandom_v emap=ext normed=True bTree=True
cmsRun recHitRAW_cfg.py runNumber=325994 runInputDir=/eos/cms/store/express/HIRun2018/HIExpressPhysics/FEVT/Express-v1/000/ source=PoolSource rawTag='' outputTag=_normedRandomTree hlt=HLT_HIRandom_v emap=ext normed=True bTree=True
